config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations', omniauth_callbacks: 'users/omniauth_callbacks' }

  root 'posts#index'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :users, only: [:show, :create, :index] do
    patch 'update_profile_picture', on: :member
    resources :friendships, only: [:index, :new, :create, :update, :destroy]
    resources :posts, except: [:index] do
      resources :likes, only: [:new, :create, :destroy]
      resources :comments
    end
  end
  resources :comments do
    resources :comments
    resources :likes, only: [:create, :destroy]
  end
  resources :posts, only: [:index]

  namespace :users do
    resources :friends, only: [:index, :destroy], path: "/:id/friends", as: :user_friends
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  include Likeable

  belongs_to :author, class_name: 'User'
  belongs_to :commentable, polymorphic: true
  belongs_to :parent, optional: true, class_name: "Comment"
  has_many :comments, foreign_key: :parent_id, dependent: :destroy
  has_many :likes, as: :likeable, dependent: :destroy
  has_many :liking_users, through: :likes, source: :user

  validates :content, length: { in: 1..500 }

  def self.show_comments(post)
    Comment.where(post: post)
  end
end

app/controllers/comments/comments_controller.rb
class Comments::CommentsController < ApplicationController
  include Commentable

  before_action :set_commentable

  private

  def set_commentable
    @parent = Comment.find(params[:comment_id])
    @commentable = @parent.commentable # Post
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    set_post
    set_user

    @comment = Comment.new
  end

  def create
    set_commentable

    @comment = Comment.new(
      comment_params.merge(commentable: @commentable, author: current_user)
    )
    @comment.parent_id = @parent&.id

    respond_to do |format|
      if @comment.save
        if @parent
          format.turbo_stream {
            render turbo_stream: turbo_stream.append(@parent, @comment)
          }
        else
          format.turbo_stream {
            render turbo_stream: turbo_stream.append("comment_#{@commentable.id}", @comment)
          }
        end
        format.html {
          redirect_to user_path(@commentable.author),
          notice: "Comment was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def index
    set_post
    @comments = Comment.show_comments(@post)
  end

  def show
    set_comment
  end

  def edit
    set_comment
  end

  def update
    set_comment

    return unauthorized unless current_user == @comment.author

    respond_to do |format|
      if @comment.update(comment_params)
        format.html {
          redirect_to user_path(@comment.commentable.author),
          notice: "Comment was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    set_comment

    return unauthorized unless current_user == @comment.author

    @comment.destroy
    respond_to do |format|
      format.turbo_stream {
        render turbo_stream: turbo_stream.remove(@comment)
      }
      format.html {
        redirect_to posts_url,
        notice: 'Post was successfully destroyed.' }
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end

  def unauthorized
    flash[:alert] = 'You are not authorized to do that'
    redirect_to root_path
  end

  def set_post
    @post = Post.find(params[:post_id])
  end

  def set_user
    @user = User.find(params[:user_id])
  end

  def set_comment
    return @comment = Comment.find(params[:comment_id]) if params[:comment_id]

    @comment = Comment.find(params[:id])
  end

  def set_commentable
    if params[:comment_id]
      set_parent
      @commentable = @parent.commentable
    elsif params[:post_id]
      @commentable = set_post
    end
  end

  def set_parent
    @parent = Comment.find(params[:comment_id])
  end
end

app/controllers/posts/comments_controller.rb
class Posts::CommentsController < ApplicationController
  include Commentable

  before_action :set_commentable

  private

  def set_commentable
    @commentable = Post.find(params[:post_id])
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
  <div class="comment-box">
    <%= turbo_frame_tag "comment_#{comment.id}" do %>
      <ul class="comment-container">
        <div class="single-comment-container">
          <li class="profile-image-small profile-image-line">
            <% if comment.author.profile_picture.attached? %>
              <%= image_tag comment.author.profile_picture %>
            <% else %>
              <%= image_tag comment.author.gravatar_url %>
            <% end %>
            <%= comment.author.fullname %></li>
          <li class="post-content"><%= comment.content %></li>
          <ul class="comment-btns">
            <% if current_user == comment.author %>
              <li class="edit-btn">
                <%= link_to 'Edit Comment',
                  edit_user_post_comment_path(comment.author, comment.commentable, comment)
                %>
                </li>
              <li class="delete-btn">
                <%= button_to "Delete Comment",
                  user_post_comment_path(comment.author, comment.commentable, comment),
                  method: :delete %>
              </li>
            <% end %>
              <%# render 'likes/like', likeable: comment %>
            <% if comment.liking_users.include?(current_user) %>
                <%= button_to "Unlike", comment_like_path(comment, comment.likes.where(user_id: current_user.id).take), method: :delete, class: 'unlike-btn' %>
              <% else %>
                <%= form_with url: comment_likes_path(comment),
                  method: :post, class: "like-btn" do |f| %>
                  <%= f.submit 'Like' %>
                <% end %>
              <% end %>
          </ul>
          <li class= "likes-message">
            <%= comment.display_likes %>
          </li>

          <li class="comment-reply-item">
            <%= form_for [comment, Comment.new],
            data: { controller: 'form', action: 'turbo:submit-end->form#reset' } do |f| %>
              <%= f.text_field :content, placeholder: 'Write a comment...', data: { 'form-target': 'contentField' } %>
              <%= f.submit "Reply", class: 'reply-btn'  %>
            <% end %>
          </li>
        </div>



            <%= render partial: 'comments/comment', collection: comment.comments %>

      <% end %>
      </ul>
  </div>

app/views/comments/_comment_with_replies.html.erb
<%= turbo_stream_from comment, :comments %>

<div class="comment-replies" id="<%= dom_id(comment) %>_with_comments" data-controller="comment-reply">
  <%= render comment %>

  <div>
    <%= link_to "Reply", "#", data: { action: "click->comment-reply#toggle" } %>
  </div>

  <div id="<%= dom_id(comment) %>_comments">
    <%= render partial: "comments/form", locals: { commentable: comment, comment: Comment.new, data: { comment_reply_target: "form"}, class: 'hidden-form' } %>
    <%= render partial: "comments/comment_with_replies", collection: comment.comments, as: :comment %>
  </div>
</div>

app/views/comments/_form.html.erb
<%= form_with model: comment,
    url: comment.persisted? ? user_post_comment_path(comment.commentable.author, comment.commentable, comment) : user_post_comments_path(@user, @post),
    method: comment.persisted? ? :patch : :post, data: { controller: 'form', action: 'turbo:submit-end->form#reset' } do |form| %>
    <% if comment.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

        <ul>
          <% comment.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div>
      <%= form.label :content, ': ', class: "hidden" %>
      <%= form.text_field :content, placeholder: 'Write a comment...', data: { 'form-target': 'contentField' } %>
    </div>
    <div class="comment-submit-btn">
      <%= form.submit %>
    </div>
  <% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= turbo_frame_tag @comment do %>
  <%= render "form", comment: @comment %>
  <div><%= link_to 'Back', user_path(@comment.commentable.author),
    data: { turbo_frame: "_top" } %></div>
<% end %>

app/views/comments/index.html.erb
  <p style="color: green"><%= notice %></p>

  <h1>Comments</h1>

  <div id="comments">
    <ul>
      <% @comments.each do |post| %>
        <li>Content: <br /><%= comment.content %></li>
      <% end %>
    </ul>
  </div>

app/views/comments/new.html.erb
<%= turbo_frame_tag id='new_comment' do %>
    <%= render "form", comment: @comment %>
  <% end %>

app/views/comments/show.html.erb
<%= turbo_frame_tag @comment do %>
  <%= render @comment %>
<% end %>