config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations', omniauth_callbacks: 'users/omniauth_callbacks' }

  root 'posts#index'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :users, only: [:show, :create, :index] do
    patch 'update_profile_picture', on: :member
    resources :friendships, only: [:index, :new, :create, :update, :destroy]
    resources :posts, except: [:index] do
      resources :likes, only: [:new, :create, :destroy]
      resources :comments
    end
  end
  resources :comments do
    resources :comments
    resources :likes, only: [:create, :destroy]
  end
  resources :posts, only: [:index]

  namespace :users do
    resources :friends, only: [:index, :destroy], path: "/:id/friends", as: :user_friends
  end
end

app/models/post.rb
class Post < ApplicationRecord
  include Likeable

  belongs_to :postable, polymorphic: true
  belongs_to :author, class_name: 'User'
  has_many :likes, as: :likeable, dependent: :destroy
  has_many :liking_users, through: :likes, source: :user
  has_many :comments, as: :commentable, dependent: :destroy

  around_destroy :destroy_associated_post

  def self.show_posts(user)
    Post.where(author: user)
  end

  # changes the created at date of the post to be human readable
  def formatted_date
    created_at.strftime('%B %e at %-l:%M %p')
  end

  def self.reverse_chronological
    order("created_at DESC")
  end

  def destroy_associated_post
    postable.destroy
    yield
  end
end

app/controllers/posts/comments_controller.rb
class Posts::CommentsController < ApplicationController
  include Commentable

  before_action :set_commentable

  private

  def set_commentable
    @commentable = Post.find(params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:show]

  # GET /posts or /posts.json
  def index
    @posts = Post.reverse_chronological
  end

  # GET /posts/1 or /posts/1.json
  def show
    set_post
  end

  # GET /posts/new
  def new
    set_user

    if current_user == @user
      @post = Post.new
    else
      unauthorized
    end
  end

  # GET /posts/1/edit
  def edit
    set_user
    return unauthorized unless current_user == @user

    set_post
  end

  # POST /posts or /posts.json
  def create
    @postable = find_post_type

    @post = current_user.posts.build(postable: @postable)
    set_user

    return unauthorized unless current_user == @user

    respond_to do |format|
      if @post.save
        format.turbo_stream {
          render turbo_stream: turbo_stream.prepend('posts', @post)
        }
        format.html {
          redirect_to root_path,
          notice: "Post was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    set_user
    set_post
    @postable = find_post_type
    return unauthorized unless current_user == @user

    respond_to do |format|
      if @post.update(postable: @postable)
        format.html {
          redirect_to user_path(current_user),
          notice: "Post was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    set_post
    set_user

    return unauthorized unless current_user == @user

    @post.destroy
    respond_to do |format|
      format.turbo_stream {
        render turbo_stream: turbo_stream.remove(@post)
      }
      format.html {
        redirect_to posts_url,
        notice: 'Post was successfully destroyed.' }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  def set_user
    @user = User.find(params[:user_id])
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:content, :image)
  end

  def unauthorized
    flash[:alert] = 'You are not authorized to do that'
    redirect_to root_path
  end

  # Assigns correct postable
  def find_post_type
    return TextPost.new(post_params) unless post_params[:content].empty?

    if !post_params[:image].nil?
      return upload_image if upload_image
    else
      render :new, status: :unprocessable_entity, notice: 'Invalid Post object.'
    end
    render :new, status: :unprocessable_entity, notice: 'Invalid Post object.'
  end

  def upload_image
    @image_post = ImagePost.new

    if @image_post.save
      @image_post.image.attach(post_params[:image])
      @image_post
    else
      render :new, status: :unprocessable_entity, notice: 'Invalid ImagePost object.'
      false
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<div class="post-form-container">

    <%= form_with model: post,
      url: post.persisted? ? user_post_path(@user, post) : user_posts_path(@user),
      method: post.persisted? ? :patch : :post, data: { controller: 'form', action: 'turbo:submit-end->form#reset' } do |form| %>
      <% if post.errors.any? %>
        <div style="color: red">
          <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

          <ul>
            <% post.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="new-post-entry">
        <%= form.label :content, ' :', class: "hidden" %>
        <%= form.text_field :content,
          placeholder: "What's on your mind, #{current_user.first_name}?", data: { 'form-target': 'contentField' } %>
        <div class="post-btn-container">
          <%= form.label :image do %>
            <%= image_tag "attach-image.svg", alt: "attach image"  %>
          <% end %>
          <div class="hidden"><%= form.file_field :image %></div>
          <div class="post-btn">
            <%= form.submit %>
          </div>
        </div>
      </div>
    <% end %>
</div>

app/views/posts/_new_post.html.erb
<div class="new-posts-link">
  <%= turbo_frame_tag  id="new_post", src:new_user_post_path(user) %>
</div>

app/views/posts/_post.html.erb
<% if current_user.friend_list.include?(post.author)  ||
  current_user == post.author %>
  <div class="post-box main-post-box" data-controller="time">
    <%= turbo_frame_tag post do %>
      <ul class="post-box">
        <div class="post-container">
          <li class="profile-image-small profile-image-line">
            <% if post.author.profile_picture.attached? %>
              <%= image_tag post.author.profile_picture %>
            <% else %>
              <%= image_tag post.author.gravatar_url %>
            <% end %>
            <%= post.author.fullname %></li>
          <li data-time-target="postTime" class="post-time"><%= post.created_at %></li>
          <li class='post-content'>
            <% if post.postable_type == 'TextPost' %>
              <%= post.postable.content %>
            <% else %>
              <%= image_tag post.postable.image, class: 'post-image' %>
            <% end %>
          </li>
            <ul class="post-btns">
              <% if current_user == post.author %>
                <li class="edit-btn">
                  <%= link_to 'Edit Post', edit_user_post_path(post.author, post) %>
                </li>
                <li>
                  <%= button_to "Delete Post", user_post_path(post.author, post),
                  method: :delete %>
                </li>
              <% end%>
              <%= render 'likes/like', likeable: post %>
            </ul>
        </div>
        <div class="new-comment-link comment-reply-item">
          <%= turbo_frame_tag  id="new_comment", src:new_user_post_comment_path(post.author, post) %>
        </div>

        <% post.comments.where(parent_id: nil).each do |comment| %>
          <%= render 'comments/comment', comment: comment %>
        <% end %>
        <li>

        </li>

      </ul>
    <% end %>

  </div>
<% end %>

app/views/posts/_posts.html.erb
<div id="posts">
  <%= render @posts.reverse_chronological %>
</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= turbo_frame_tag @post do %>
  <%= render "form", post: @post %>
  <div><%= link_to 'Back', user_path(current_user),
    data: { turbo_frame: "_top" } %></div>
<% end %>

app/views/posts/index.html.erb
<div class="main-container">

  <%= render 'new_post', user: current_user %>

  <%= render 'posts'%>

  <div class="friends-list">
    <div>Friend <span>List</span></div>
    <ul>
      <% current_user.friends.each do |friend| %>
        <li>
          <ul class="friend-link">
            <%= link_to user_path(friend) do %>
              <li>
                <%= truncate(friend.fullname, length: 14) %>
              </li>
              <li>
                <% if friend.profile_picture.attached? %>
                  <%= image_tag friend.profile_picture,
                  class: "profile-image-med" %>
                <% else %>
                  <%= image_tag friend.gravatar_url,
                  class: "profile-image-med" %>
                <% end %>
              </li>
            <% end %>
          </ul>
        </li>
      <% end %>
        <li class="additional-friends-link">
          <%= link_to "See all friends", users_user_friends_path(current_user) %>
        </li>
    </ul>
  </div>
</div>

app/views/posts/new.html.erb
<h1>New post</h1>

  <%= turbo_frame_tag id='new_post' do %>
    <%= render "form", post: @post %>

  <% end %>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @post %>

      <%= render partial: 'comments/form', locals: { comment: Comment.new, commentable: @post } %>