config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations', omniauth_callbacks: 'users/omniauth_callbacks' }

  root 'posts#index'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :users, only: [:show, :create, :index] do
    patch 'update_profile_picture', on: :member
    resources :friendships, only: [:index, :new, :create, :update, :destroy]
    resources :posts, except: [:index] do
      resources :likes, only: [:new, :create, :destroy]
      resources :comments
    end
  end
  resources :comments do
    resources :comments
    resources :likes, only: [:create, :destroy]
  end
  resources :posts, only: [:index]

  namespace :users do
    resources :friends, only: [:index, :destroy], path: "/:id/friends", as: :user_friends
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>The Hub</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="main-nav">
        <ul>
          <li class="site-name">
            <%= link_to 'The Hub', root_path %>
          </li>
          <% unless user_signed_in? %>
            <li class="sign-in-links">
              <ul>
                <li class="link-btn">
                  <%= link_to "Sign up here", new_user_registration_path %>
                </li>
                <li class="link-btn">
                  <%= link_to "Sign in", user_session_path %>
                </li>
              </ul>
            </li>
          <% end %>
           <li class="flash-message">
            <% flash.each do |name, message| %>
              <div class="<%= name %>"><%= message %></div>
            <% end %>
          </li>
          <% if user_signed_in? %>
            <li>
              <div class="user-list">
                <%= link_to users_path do %>
                  <%= image_tag "friends-icon.svg" %>
                <% end %>
              </div>
            </li>
          <% end %>
          <% if user_signed_in? %>
            <div class="notification-icon dropdown">
              <span>
                <%= image_tag "bell-icon.svg", class: 'notification-img' %>
              </span>
              <% if current_user.friend_requests? %>
                <span class="notify">
                  !
                </span>
              <% end %>
              <div class="notification-dropdown dropdown-content">
                <% if current_user.friend_requests? %>
                  <p>
                    You have a new friend request:
                    <br/>
                    <%= link_to "click here to see your new friend request", user_friendships_path(current_user), class: "notification-link" %>
                  </p>
                <% else %>
                  <p>You have no new notifications</p>
                <% end %>
              </div>
            </div>
          <% end %>
          <% if user_signed_in? %>
            <li class="user-picture">
              <ul>
                <li class="log-out-btn link-btn">
                  <%= button_to "Logout", destroy_user_session_path, method: :delete  %>
                </li>
                <li>
                  <% if current_user.profile_picture.attached? %>
                    <%= link_to user_path(current_user) do %>
                      <%= image_tag current_user.profile_picture, class: "profile-image-med" %>
                    <% end %>
                  <% else %>
                    <%= link_to user_path(current_user) do %>
                      <%= image_tag current_user.gravatar_url, class: "profile-image-med" %>
                    <% end %>
                  <% end %>
                </li>
              </ul>
            </li>
          <% end %>
        </ul>
      </nav>
      <%= yield %>
  </body>
</html>